### ISSUE TITLE
WEbite is blank

### ISSUE THREAD

**Issue by BlooketHackerx** [ThatFruedDued/blooket-utility#67] opened 2022-03-01 16:23 UTC
WHen I opened the utility website it was completely blank. WHat is happening?

**Comment by ThatFruedDued** [comment] 2022-03-01 18:15
I am unable to reproduce this issue. If possible, please send a screenshot of the output of the developer console.

**Comment by Blooket-dude** [comment] 2022-03-01 19:57
@BlooketHackerx both are working fine for me!

**Comment by ThatFruedDued** [comment] 2022-03-02 15:24
Unfortunately, I'm closing this issue because I cannot reproduce and you cannot provide enough information for me to understand the problem. If someone can reproduce this issue and has access to the developer console, please create a new issue so I can try to fix it.

**Closed by ThatFruedDued** 2022-03-02 15:24 UTC
