### ISSUE TITLE
it takes me to the sign in page

### ISSUE THREAD

**Issue by ufehurh** [ThatFruedDued/blooket-utility#87] opened 2022-05-19 18:18 UTC
if i then try to leave that page it takes me to the normal page. I cant join a game or sign in.is there a way to join a game or a url that takes you to join a game?

**Comment by ThatFruedDued** [comment] 2022-05-19 20:53
If you are attempting to sign in with Google, please first sign into <https://dashboard.blooket.com>, add a Blooket password to your account, then sign in using that. **It is not possible to integrate with Google services without permission from Blooket which won't happen.**

**Comment by VillainsRule4000** [comment] 2022-05-19 21:02
@ThatFruedDued FINALLY RESOLVING ISSUES THANK YOU SO MUCH

**Comment by ThatFruedDued** [comment] 2022-05-21 19:28
Duplicate of #59

**Closed by ThatFruedDued** 2022-05-21 19:28 UTC
